# -*- coding: utf-8 -*-
"""Project#2-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kB5VdlPSRQEGKexYqwGi3eYFA8BqcCxp
"""

import pandas as pd

file_path = '2019_kbo_for_kaggle_v2.csv'

data = pd.read_csv(file_path)
df = pd.DataFrame(data)

#1
#Print the top 10 players in hits, batting average, homerun, and onbase percentage for each year from 2015 to 2018.

list_year = [2015,2016, 2017, 2018]

for i in list_year:
    df_year = df[(df['year'] == i)]
    df_H = df_year.sort_values(by='H',ascending=False).head(10)
    df_avg = df_year.sort_values(by='avg',ascending=False).head(10)
    df_HR = df_year.sort_values(by='HR',ascending=False).head(10)
    df_OBP = df_year.sort_values(by='OBP',ascending=False).head(10)

    list_H = list(df_H['batter_name'])
    list_avg = list(df_avg['batter_name'])
    list_HR = list(df_HR['batter_name'])
    list_OBP = list(df_OBP['batter_name'])

    top_10_player = {'H':list_H,
                    'avg':list_avg,
                    'HR':list_HR,
                    'OBP':list_OBP}

    print(i,"top 10 player")
    print(pd.DataFrame(top_10_player))
    print()

#2
#Print the player with the highest war (승리 기여도) by position (cp) in 2018.

df_filter_year = df[df['year'] == 2018]
df_war = df_filter_year.sort_values(by='war', ascending=False)
position_list = ['포수', '1루수', '2루수', '3루수', '유격수', '좌익수', '중견수', '우익수']

print('player with the highest war by position in 2018')

for i in position_list:
    position_data = df_war[df_war['cp'] == i]

    top_player = position_data.iloc[0]
    print(i,':',top_player['batter_name'])

#3
#Among R, H, HR, RBI, SB, war, avg, OBP, SLG which has the highest correlation with salary?

corr = 0
col = ''
list_col = ['R', 'HR', 'RBI', 'SB', 'war', 'avg', 'OBP', 'SLG']

for i in list_col:
    cal_corr = df['salary'].corr(df[i])
    if abs(cal_corr) > abs(corr):
        corr = cal_corr
        col = i

print("highest correlation with salary:", col)
print("correlation:", corr)